# Generated by Django 2.1.4 on 2018-12-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181218_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answered_by_email',
            field=models.CharField(default='No Account', max_length=512),
        ),
        migrations.AlterField(
            model_name='question',
            name='author_email',
            field=models.CharField(default='No Account', max_length=512),
        ),
    ]
