# Generated by Django 2.1.4 on 2019-07-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_feedback_for_q'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='most_recent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question', unique=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='num_questions_asked',
            field=models.IntegerField(default=0),
        ),
    ]
