# Generated by Django 2.1.4 on 2018-12-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Penn Email Address'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
