# Generated by Django 2.1.4 on 2018-12-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='is_ta',
            field=models.BooleanField(default=False, verbose_name='Teaching Assistant'),
        ),
    ]
