# Generated by Django 2.1.4 on 2019-01-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181225_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(max_length=64, unique=True, verbose_name='Penn Email Address'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
    ]
