# Generated by Django 2.1.4 on 2019-07-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190720_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='most_recent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question', unique=True),
        ),
    ]
