# Generated by Django 2.1.4 on 2018-12-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.CharField(default='No Account', max_length=512)),
                ('answered_by_email', models.CharField(default='No Account', max_length=512)),
                ('status', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=280)),
                ('ask_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
