# Generated by Django 2.1.4 on 2019-07-29 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.CharField(default='No Account', max_length=64)),
                ('author_first_name', models.CharField(default='No first name', max_length=32)),
                ('author_last_name', models.CharField(default='No last name', max_length=32)),
                ('answered_by_email', models.CharField(default='No Account', max_length=64)),
                ('answerer_first_name', models.CharField(default='', max_length=32)),
                ('answerer_last_name', models.CharField(default='', max_length=32)),
                ('is_answered', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=280)),
                ('ask_date', models.DateTimeField(auto_now_add=True)),
                ('host_queue', models.CharField(default='', max_length=32)),
                ('feedback_for_q', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback', unique=True)),
            ],
        ),
    ]
