# Generated by Django 2.1.4 on 2019-01-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181225_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answered_by_email',
            field=models.CharField(default='No Account', max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='author_email',
            field=models.CharField(default='No Account', max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='author_first_name',
            field=models.CharField(default='No first name', max_length=32),
        ),
        migrations.AlterField(
            model_name='question',
            name='author_last_name',
            field=models.CharField(default='No last name', max_length=32),
        ),
    ]
