# Generated by Django 2.1.4 on 2018-12-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20181218_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered_by',
        ),
        migrations.AddField(
            model_name='question',
            name='answered_by_email',
            field=models.CharField(default='yo', max_length=512),
            preserve_default=False,
        ),
    ]
