# Generated by Django 2.1.4 on 2019-07-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('questions', '0006_question_host_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='feedback_for_q',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback', unique=True),
        ),
    ]
