# Generated by Django 2.1.4 on 2019-07-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_feedback_for_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='feedback_for_q',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback', unique=True),
        ),
    ]
