# Generated by Django 2.1.4 on 2018-12-19 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0006_auto_20181218_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('average_wait_time', models.FloatField(default=0.0)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
    ]
