# Generated by Django 2.1.4 on 2019-08-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_open_extended', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_in_time', models.BooleanField(default=False)),
                ('show_ewt', models.BooleanField(default=True)),
                ('monday_times', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('tuesday_times', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('wednesday_times', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('thursday_times', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('friday_times', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('saturday_times', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sunday_times', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('average_wait_time', models.FloatField(default=0.0)),
                ('num_questions_answered', models.IntegerField(default=0)),
                ('last_answer_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('questions', models.ManyToManyField(blank=True, to='questions.Question')),
            ],
            options={
                'verbose_name_plural': 'Office Hours Queues',
                'verbose_name': 'Office Hours Queue',
            },
        ),
    ]
