# Generated by Django 2.1.4 on 2018-12-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohqueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohqueue',
            name='questions',
            field=models.ManyToManyField(blank=True, to='questions.Question'),
        ),
    ]
