# Generated by Django 2.1.4 on 2018-12-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohqueue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohqueue',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='ohqueue',
            name='start_time',
        ),
        migrations.AddField(
            model_name='ohqueue',
            name='times_open',
            field=models.CharField(default='yo', max_length=1024),
            preserve_default=False,
        ),
    ]
