# Generated by Django 2.1.4 on 2018-12-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohqueue', '0002_auto_20181224_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohqueue',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
