# Generated by Django 2.1.4 on 2018-12-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohqueue', '0003_auto_20181225_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohqueue',
            name='is_closed_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ohqueue',
            name='is_open_extended',
            field=models.BooleanField(default=False),
        ),
    ]
