# Generated by Django 2.1.4 on 2018-12-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohqueue', '0004_auto_20181219_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohqueue',
            name='questions',
            field=models.ManyToManyField(to='questions.Question'),
        ),
    ]
