# Generated by Django 2.1.4 on 2018-12-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohqueue', '0004_auto_20181229_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ohqueue',
            old_name='is_closed_early',
            new_name='is_closed',
        ),
        migrations.AddField(
            model_name='ohqueue',
            name='is_in_time',
            field=models.BooleanField(default=False),
        ),
    ]
