# Generated by Django 2.1.4 on 2018-12-31 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohqueue', '0006_auto_20181229_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohqueue',
            name='last_answer_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
