# Generated by Django 2.1.4 on 2018-12-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohqueue', '0007_auto_20181231_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohqueue',
            name='last_answer_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
