# Generated by Django 2.1.4 on 2019-01-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohqueue', '0008_auto_20181231_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohqueue',
            name='times_open',
        ),
        migrations.AddField(
            model_name='ohqueue',
            name='friday_times',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ohqueue',
            name='monday_times',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ohqueue',
            name='saturday_times',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ohqueue',
            name='sunday_times',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ohqueue',
            name='thursday_times',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ohqueue',
            name='tuesday_times',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ohqueue',
            name='wednesday_times',
            field=models.CharField(default='', max_length=50),
        ),
    ]
