# Generated by Django 2.1.4 on 2019-01-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohqueue', '0011_auto_20190107_0248'),
        ('ohqueue', '0010_auto_20190106_2343'),
    ]

    operations = [
    ]
