# Generated by Django 2.1.4 on 2019-01-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohqueue', '0013_ohqueue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohqueue',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
