# Generated by Django 2.1.4 on 2019-01-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohqueue', '0014_auto_20190109_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohqueue',
            name='show_ewt',
            field=models.BooleanField(default=True),
        ),
    ]
