# Generated by Django 2.1.4 on 2019-07-20 16:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0006_question_host_queue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_scale', models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('thumbs_up', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=280)),
                ('feedback_time', models.DateTimeField(auto_now_add=True)),
                ('base_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question', unique=True)),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
