# Generated by Django 2.1.4 on 2019-07-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='thumbs_up',
            new_name='was_helpful',
        ),
    ]
