# Generated by Django 2.1.4 on 2018-12-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181216_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='is_ta',
            field=models.BooleanField(default=False),
        ),
    ]
